### ISSUE TITLE
review and update all of the project dependency versions

### ISSUE THREAD

**Issue by loomis** [slipstream/SlipStream#42]
Review the updates that are available for the SlipStream dependencies.  Unless there is a good reason not to move to the latest production release of a dependency, update the dependency.

**Comment by schaubl** [comment]
For `libcloud` we cannot update the version (in this task) because some methods was removed/renamed.
So we can update it but it will require a separate task because all libcloud dependent connector will have to be checked and updated.

**Comment by loomis** [comment]
The following provides the list of maven-managed dependency updates that are available:
```
[INFO]   clj-stacktrace:clj-stacktrace ......................... 0.2.7 -> 0.2.8
[INFO]   clj-time:clj-time ..................................... 0.8.0 -> 0.9.0
[INFO]   clojure-complete:clojure-complete ..................... 0.2.3 -> 0.2.4
[INFO]   com.fasterxml.jackson.core:jackson-databind ........... 2.2.3 -> 2.5.3
[INFO]   com.google.code.gson:gson ............................... 2.1 -> 2.3.1
[INFO]   com.google.guava:guava .................................. 13.0 -> 18.0
[INFO]   com.jcraft:jsch ..................................... 0.1.49 -> 0.1.52
[INFO]   com.mchange:c3p0 .............................. 0.9.2.1 -> 0.9.5-pre10
[INFO]   com.taoensso:tower .............................. 3.0.2 -> 3.1.0-beta3
[INFO]   commons-codec:commons-codec .............................. 1.4 -> 1.10
[INFO]   commons-lang:commons-lang ................................. 2.3 -> 2.6
[INFO]   compojure:compojure ................................... 1.1.8 -> 1.3.3
[INFO]   enlive:enlive ......................................... 1.1.4 -> 1.1.5
[INFO]   expectations:expectations ............................. 2.0.9 -> 2.1.1
[INFO]   http-kit:http-kit ................................... 2.1.18 -> 2.1.19
[INFO]   javax.mail:mail ................................... 1.4.1 -> 1.5.0-b01
[INFO]   javax.servlet:servlet-api ......................... 2.5 -> 3.0-alpha-1
[INFO]   jline:jline ......................................... 0.9.94 -> 2.12.1
[INFO]   junit:junit ............................................ 4.8.2 -> 4.12
[INFO]   metrics-clojure:metrics-clojure ....................... 2.1.0 -> 2.5.1
[INFO]   metrics-clojure-jvm:metrics-clojure-jvm ............... 2.1.0 -> 2.5.1
[INFO]   metrics-clojure-ring:metrics-clojure-ring ............. 2.1.0 -> 2.5.1
[INFO]   net.cgrand:moustache ........................... 1.1.0 -> 1.2.0-alpha2
[INFO]   net.kencochrane.raven:raven ........................... 4.1.1 -> 6.0.0
[INFO]   net.sf.flexjson:flexjson .................................. 3.2 -> 3.3
[INFO]   org.clojure:clojure ............................. 1.6.0 -> 1.7.0-beta2
[INFO]   org.clojure:core.async ...
[INFO]                         0.1.267.0-0d7780-alpha -> 0.1.346.0-17112a-alpha
[INFO]   org.clojure:data.json ................................. 0.2.5 -> 0.2.6
[INFO]   org.clojure:tools.logging ............................. 0.3.0 -> 0.3.1
[INFO]   org.clojure:tools.namespace .......................... 0.2.5 -> 0.2.10
[INFO]   org.clojure:tools.nrepl .............................. 0.2.6 -> 0.2.10
[INFO]   org.hamcrest:hamcrest-all ................................. 1.1 -> 1.3
[INFO]   org.hibernate:hibernate-c3p0 .............. 4.3.5.Final -> 5.0.0.Beta2
[INFO]   org.hibernate:hibernate-entitymanager ..... 4.3.5.Final -> 5.0.0.Beta2
[INFO]   org.json:json ................................... 20140107 -> 20141113
[INFO]   org.restlet.jee:org.restlet .......................... 2.2.1 -> 3.0-M1
[INFO]   org.restlet.jee:org.restlet.ext.fileupload ........... 2.2.1 -> 3.0-M1
[INFO]   org.restlet.jee:org.restlet.ext.httpclient ........... 2.2.1 -> 3.0-M1
[INFO]   org.restlet.jee:org.restlet.ext.servlet .............. 2.2.1 -> 3.0-M1
[INFO]   org.restlet.jee:org.restlet.ext.xml .................. 2.2.1 -> 3.0-M1
[INFO]   org.seleniumhq.selenium:selenium-java ............... 2.15.0 -> 2.45.0
[INFO]   org.simpleframework:simple-xml ........................ 2.2.4 -> 2.7.1
[INFO]   org.slf4j:slf4j-api .................................. 1.7.7 -> 1.7.12
[INFO]   org.slf4j:slf4j-jdk14 ................................ 1.7.7 -> 1.7.12
[INFO]   org.slf4j:slf4j-log4j12 .............................. 1.7.7 -> 1.7.12
[INFO]   org.xerial:sqlite-jdbc ................................ 3.7.2 -> 3.8.7
[INFO]   peridot:peridot ....................................... 0.3.0 -> 0.3.1
[INFO]   prismatic:schema ...................................... 0.2.6 -> 0.4.2
[INFO]   reply:reply ........................................... 0.3.4 -> 0.3.7
[INFO]   ring:ring ....................................... 1.1.8 -> 1.4.0-beta1
[INFO]   ring:ring-core .................................. 1.3.0 -> 1.4.0-beta1
```

**Comment by loomis** [comment]
The following is the current report after updating all dependencies that allow the compile, build, and test to complete normally.  (The resulting server has not been tested for functionality.)
```
[INFO]   com.mchange:c3p0 ................................ 0.9.5 -> 0.9.5-pre10
[INFO]   com.taoensso:tower .............................. 3.0.2 -> 3.1.0-beta3
[INFO]   javax.mail:mail ................................... 1.4.7 -> 1.5.0-b01
[INFO]   javax.servlet:servlet-api ......................... 2.5 -> 3.0-alpha-1
[INFO]   net.cgrand:moustache ........................... 1.1.0 -> 1.2.0-alpha2
[INFO]   org.clojure:clojure ............................. 1.6.0 -> 1.7.0-beta2
[INFO]   org.clojure:core.async ...
[INFO]                         0.1.267.0-0d7780-alpha -> 0.1.346.0-17112a-alpha
[INFO]   org.hibernate:hibernate-c3p0 .............. 4.3.9.Final -> 5.0.0.Beta2
[INFO]   org.hibernate:hibernate-entitymanager ..... 4.3.9.Final -> 5.0.0.Beta2
[INFO]   org.restlet.jee:org.restlet .......................... 2.2.1 -> 3.0-M1
[INFO]   org.restlet.jee:org.restlet.ext.fileupload ........... 2.2.1 -> 3.0-M1
[INFO]   org.restlet.jee:org.restlet.ext.httpclient ........... 2.2.1 -> 3.0-M1
[INFO]   org.restlet.jee:org.restlet.ext.servlet .............. 2.2.1 -> 3.0-M1
[INFO]   org.restlet.jee:org.restlet.ext.xml .................. 2.2.1 -> 3.0-M1
[INFO]   ring:ring ....................................... 1.3.2 -> 1.4.0-beta1
[INFO]   ring:ring-core .................................. 1.3.2 -> 1.4.0-beta1
```
All of these are on the latest production release, except for:
  - org.clojure:clojure
  - org.clojure:core.async
  - org.restlet.jee:org.restlet*
Upgrading the above will require changes to the code.  See following comments for details.

**Comment by loomis** [comment]
The latest Clojure version is nearing a production release.  It brings many performance improvements as well as new features such as transducers, which are likely to be useful when transforming our resources for consumption by the API users.

Use of the 1.7.0 causes the following issues:
  - Warning about replacement of `clojure.core/update`: in the UI, clojure resource server, and OCCI connector.  The namespaces are:
    * `korma.core` (external dependency)
    * `slipstream.ui.models.parameters`
    * `com.sixsq.slipstream.ssclj.api.acl`
    * `com.sixsq.slipstream.ssclj.db.database-binding`
    * `com.sixsq.slipstream.ssclj.resources.usage`
    * `com.sixsq.slipstream.ssclj.db.database-binding-delete-test`
    * `com.sixsq.slipstream.ssclj.db.database-binding-test`
    * `com.sixsq.slipstream.ssclj.usage.record-keeper-test`
    * `com.sixsq.slipstream.ssclj.usage.summary-test`
    * `com.sixsq.slipstream.ssclj.usage.summary-volume-test`
    * `slipstream.credcache.credential`
  - `test-summarize-and-store` fails because of an map key order dependency when comparing strings

The warnings can be fixed by adding the following line to the `ns` declarations:
```
(:refer-clojure :exclude [update])
```
Or by renaming the SlipStream method to something else. 

The only blocking issue is the test failure.

**Comment by loomis** [comment]
Updating to the latest production version of Restlet (2.3.1) causes the compilation to fail.  The problem is in `SSCLJRedirector.java`.  The problem is that the `Header` class has moved.  The following import:
```
import org.restlet.engine.header.Header;
``` 
should be changed to:
```
import org.restlet.data.Header;
```

**Comment by loomis** [comment]
Updating to the latest version of `core.async` causes compilation failures in:
  - `collector.clj`
  - `garbage_collector.clj`
  - `launcher.clj`
The problem is that the symbol `alts!` cannot be found.  This appears to be a problem with the code in that the symbol is not imported in the `ns` declaration.  This apparently only works in clojure 1.6.0 by accident.  This has been corrected in master as the compilation works correctly with the fix also in 1.6.0.

**Comment by loomis** [comment]
@rbf: Note that for the UI, there are a large number of tests that fail because of variable key ordering on the results.  (The number increases from ~20 to ~90 when switching from clojure 1.6.0 to 1.7.0-beta2.)  All of the UI tests should be systematically updated to compare data structures rather than strings.

**Comment by schaubl** [comment]
The build is currently not working for me.
I'm getting a lot of stacktraces with errors like:
- `[ERROR] Internal error: com.google.inject.ProvisionException: Guice provision errors:`
- `Caused by: java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory`
- `Caused by: java.lang.ClassNotFoundException: org.slf4j.LoggerFactory`

**Comment by schaubl** [comment]
It seems to be related to 
```diff
+      <extension>
+        <groupId>co.leantechniques</groupId>
+        <artifactId>maven-buildtime-extension</artifactId>
+        <version>2.0.1</version>
+      </extension>
```
which require `slf4j`.

**Comment by mebster** [comment]
Should we not rollback the clojure version upgrade to a later date?

**Comment by loomis** [comment]
@schaubl: It would be interesting to know how you're building SlipStream.  The builds in the CI system build correctly with the added build time maven extension.

**Comment by loomis** [comment]
@mebster, @rbf : The branch does not currently include an upgrade to clojure 1.7.  I've only include the information about the effects of this change on the build.  Nonetheless, the large number of test failures coming map key ordering changes should be systematically fixed to avoid the fragility of these comparisons.

**Comment by rbf** [comment]
> @schaubl: It would be interesting to know how you're building SlipStream. The builds in the CI system build correctly with the added build time maven extension.

@schaubl @loomis I had the same issue yesterday when building the whole app (all on `master`) after a general `git pull`. The issue was solved by deleting the local repository `.m2` and upgrading the machine's `mvn` from `3.0.5` to the latest version, i.e. `3.3.3`.

**Comment by rbf** [comment]
> @mebster, @rbf : The branch does not currently include an upgrade to clojure 1.7. I've only include the information about the effects of this change on the build. Nonetheless, the large number of test failures coming map key ordering changes should be systematically fixed to avoid the fragility of these comparisons.

1. I would definitely also wait to upgrade to 1.7 until the production release.

1. These tests had been updated and properly fixed in last iteration. However the changes were comitted into the `alice-tour` branch, since some code created in that branch was necessary for the fixes. I will be merged into master after this iteration with the whole tour. @loomis: is that tolerable?

**Comment by rbf** [comment]
> Warning about replacement of clojure.core/update

Not a big deal: it can be easily fixed in the suggested way, i.e. `(:refer-clojure :exclude [update])`, but only when we upgrade to 1.7.

**Comment by loomis** [comment]
The `(:refer-clojure :exclude [update])` fix has already been added to master; it is compatible with the current 1.6.0.

**Comment by loomis** [comment]
@schaubl: I'll update the minimum required version of maven in the `pom.xml` file.

**Comment by schaubl** [comment]
> @schaubl: It would be interesting to know how you're building SlipStream. The builds in the CI system build correctly with the added build time maven extension.
It's probably due to the fact that on CI there is a `slf4j` in the maven cache.

**Comment by loomis** [comment]
> These tests had been updated and properly fixed in last iteration. However the changes were comitted into the alice-tour branch, since some code created in that branch was necessary for the fixes. I will be merged into master after this iteration with the whole tour. @loomis: is that tolerable?

@rbf: This is ok, so long as this changes go into the next release.

**Comment by schaubl** [comment]
I updated maven to the version 3.2.5 and now the issue is solved.

**Comment by loomis** [comment]
JDK 1.7 is now in "end of life" status, meaning that it will no longer receive security updates.  All of the Java dependencies should be updated to the JDK 1.8, which has been available for sometime on CentOS 6 (and of course is in CentOS 7).

**Comment by loomis** [comment]
All of the backward compatible changes for clojure 1.7, JDK 1.8, etc. have been made directly in the repositories.  The pull request for this issue will include all dependencies upgrades listed above **except** the upgrade to clojure 1.7 and the upgrade of Restlet.  Those will be pushed off to other tickets.
