### ISSUE TITLE
Cannot build on ubuntu 14.04.1

### ISSUE THREAD

**Issue by vincent-legoll** [slipstream/SlipStream#70]
Please advise how to fix the following build failure

```
$ git clone git@github.com:slipstream/SlipStreamBootstrap.git
$ cd SlipStreamBootstrap
$ mvn generate-sources
$ cd SlipStream
$ mvn build
```
Result :

```
[INFO] Scanning for projects...
mai 29, 2015 1:56:40 PM org.sonatype.guice.bean.reflect.Logs$JULSink warn
AVERTISSEMENT: Error injecting: co.leantechniques.maven.buildtime.BuildTimeMavenLifecycleParticipant
java.lang.NoClassDefFoundError: org/slf4j/ILoggerFactory
	at org.codehaus.plexus.DefaultPlexusContainer$SLF4JLoggerFactoryProvider.get(DefaultPlexusContainer.java:873)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.getSLF4JLogger(PlexusLifecycleManager.java:231)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager$2.injectProperty(PlexusLifecycleManager.java:111)
	at org.sonatype.guice.bean.inject.BeanInjector.injectMembers(BeanInjector.java:53)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:128)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:117)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:91)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:89)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:259)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:990)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1043)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:986)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1025)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1043)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:990)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1036)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:986)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.sonatype.guice.bean.locators.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:112)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:341)
	at org.apache.maven.DefaultMaven.getLifecycleParticipants(DefaultMaven.java:538)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:270)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.slf4j.ILoggerFactory
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	... 53 more

---------------------------------------------------
constituent[0]: file:/usr/share/maven/lib/wagon-file.jar
constituent[1]: file:/usr/share/maven/lib/sisu-guice.jar
constituent[2]: file:/usr/share/maven/lib/commons-cli.jar
constituent[3]: file:/usr/share/maven/lib/guava.jar
constituent[4]: file:/usr/share/maven/lib/aether-impl.jar
constituent[5]: file:/usr/share/maven/lib/aether-api.jar
constituent[6]: file:/usr/share/maven/lib/sisu-inject-bean.jar
constituent[7]: file:/usr/share/maven/lib/maven-compat-3.x.jar
constituent[8]: file:/usr/share/maven/lib/maven-artifact-3.x.jar
constituent[9]: file:/usr/share/maven/lib/aether-util.jar
constituent[10]: file:/usr/share/maven/lib/plexus-component-annotations.jar
constituent[11]: file:/usr/share/maven/lib/plexus-sec-dispatcher.jar
constituent[12]: file:/usr/share/maven/lib/aether-connector-wagon.jar
constituent[13]: file:/usr/share/maven/lib/plexus-cipher.jar
constituent[14]: file:/usr/share/maven/lib/maven-model-builder-3.x.jar
constituent[15]: file:/usr/share/maven/lib/commons-httpclient.jar
constituent[16]: file:/usr/share/maven/lib/maven-model-3.x.jar
constituent[17]: file:/usr/share/maven/lib/aether-spi.jar
constituent[18]: file:/usr/share/maven/lib/plexus-utils.jar
constituent[19]: file:/usr/share/maven/lib/maven-core-3.x.jar
constituent[20]: file:/usr/share/maven/lib/maven-aether-provider-3.x.jar
constituent[21]: file:/usr/share/maven/lib/maven-settings-3.x.jar
constituent[22]: file:/usr/share/maven/lib/wagon-provider-api.jar
constituent[23]: file:/usr/share/maven/lib/maven-settings-builder-3.x.jar
constituent[24]: file:/usr/share/maven/lib/commons-logging.jar
constituent[25]: file:/usr/share/maven/lib/maven-embedder-3.x.jar
constituent[26]: file:/usr/share/maven/lib/maven-plugin-api-3.x.jar
constituent[27]: file:/usr/share/maven/lib/wagon-http-shaded.jar
constituent[28]: file:/usr/share/maven/lib/commons-codec.jar
constituent[29]: file:/usr/share/maven/lib/sisu-inject-plexus.jar
constituent[30]: file:/usr/share/maven/lib/maven-repository-metadata-3.x.jar
constituent[31]: file:/usr/share/maven/lib/plexus-interpolation.jar

---------------------------------------------------

Exception in thread "main" java.lang.NoClassDefFoundError: org/slf4j/ILoggerFactory
	at org.codehaus.plexus.DefaultPlexusContainer$SLF4JLoggerFactoryProvider.get(DefaultPlexusContainer.java:873)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.getSLF4JLogger(PlexusLifecycleManager.java:231)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager$2.injectProperty(PlexusLifecycleManager.java:111)
	at org.sonatype.guice.bean.inject.BeanInjector.injectMembers(BeanInjector.java:53)
	at com.google.inject.internal.MembersInjectorImpl.injectMembers(MembersInjectorImpl.java:128)
	at com.google.inject.internal.ConstructorInjector.provision(ConstructorInjector.java:117)
	at com.google.inject.internal.ConstructorInjector.access$000(ConstructorInjector.java:32)
	at com.google.inject.internal.ConstructorInjector$1.call(ConstructorInjector.java:91)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:115)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ConstructorInjector.construct(ConstructorInjector.java:89)
	at com.google.inject.internal.ConstructorBindingImpl$Factory.get(ConstructorBindingImpl.java:259)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:990)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1043)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:986)
	at com.google.inject.internal.InjectorImpl.getInstance(InjectorImpl.java:1025)
	at org.sonatype.guice.bean.reflect.AbstractDeferredClass.get(AbstractDeferredClass.java:45)
	at com.google.inject.internal.ProviderInternalFactory.provision(ProviderInternalFactory.java:84)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.provision(InternalFactoryToInitializableAdapter.java:52)
	at com.google.inject.internal.ProviderInternalFactory$1.call(ProviderInternalFactory.java:70)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:100)
	at org.sonatype.guice.plexus.lifecycles.PlexusLifecycleManager.onProvision(PlexusLifecycleManager.java:138)
	at com.google.inject.internal.ProvisionListenerStackCallback$Provision.provision(ProvisionListenerStackCallback.java:108)
	at com.google.inject.internal.ProvisionListenerStackCallback.provision(ProvisionListenerStackCallback.java:55)
	at com.google.inject.internal.ProviderInternalFactory.circularGet(ProviderInternalFactory.java:68)
	at com.google.inject.internal.InternalFactoryToInitializableAdapter.get(InternalFactoryToInitializableAdapter.java:45)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter$1.call(ProviderToInternalFactoryAdapter.java:46)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1043)
	at com.google.inject.internal.ProviderToInternalFactoryAdapter.get(ProviderToInternalFactoryAdapter.java:40)
	at com.google.inject.Scopes$1$1.get(Scopes.java:59)
	at com.google.inject.internal.InternalFactoryToProviderAdapter.get(InternalFactoryToProviderAdapter.java:41)
	at com.google.inject.internal.InjectorImpl$3$1.call(InjectorImpl.java:990)
	at com.google.inject.internal.InjectorImpl.callInContext(InjectorImpl.java:1036)
	at com.google.inject.internal.InjectorImpl$3.get(InjectorImpl.java:986)
	at org.sonatype.guice.bean.locators.LazyBeanEntry.getValue(LazyBeanEntry.java:83)
	at org.sonatype.guice.plexus.locators.LazyPlexusBean.getValue(LazyPlexusBean.java:49)
	at org.sonatype.guice.bean.locators.EntryListAdapter$ValueIterator.next(EntryListAdapter.java:112)
	at java.util.AbstractCollection.addAll(AbstractCollection.java:341)
	at org.apache.maven.DefaultMaven.getLifecycleParticipants(DefaultMaven.java:538)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:270)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.lang.ClassNotFoundException: org.slf4j.ILoggerFactory
	at org.codehaus.plexus.classworlds.strategy.SelfFirstStrategy.loadClass(SelfFirstStrategy.java:50)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.unsynchronizedLoadClass(ClassRealm.java:259)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:235)
	at org.codehaus.plexus.classworlds.realm.ClassRealm.loadClass(ClassRealm.java:227)
	... 53 more
```

**Comment by konstan** [comment]
Did you use `build` as the maven lifecycle phase or actually something else?

**Comment by konstan** [comment]
OK.  I see that the lifecycle phase doesn't matter in your case.  Looks like mvn is not able to find slf4j in the classpath.

What version of maven are you using?  `mvn -v` 

Try running `mvn build -Xe`

Do you have `org.slf4j.slf4j-api` in the local maven repo? `grep -r ILoggerFactory ~/.m2/repository/org/slf4j`  (Though, not 100% sure if mvn is going to set the classpath pointing into the local repo in this case.)

This might be useful as well:
http://stackoverflow.com/questions/18421091/exception-in-thread-main-java-lang-noclassdeffounderror-org-slf4j-iloggerfact
http://stackoverflow.com/questions/12926899/java-lang-noclassdeffounderror-org-slf4j-loggerfactory

**Comment by vincent-legoll** [comment]
```
$ mvn -v
Apache Maven 3.0.5
Maven home: /usr/share/maven
Java version: 1.7.0_79, vendor: Oracle Corporation
Java home: /usr/lib/jvm/java-7-openjdk-amd64/jre
Default locale: fr_FR, platform encoding: UTF-8
OS name: "linux", version: "3.16.0-38-generic", arch: "amd64", family: "unix"

$ grep -r ILoggerFactory ~/.m2/repository/org/slf4j
Fichier binaire /home/vlegoll/.m2/repository/org/slf4j/slf4j-api/1.7.5/slf4j-api-1.7.5.jar correspondant
```

here is the "-Xe" build output: http://paste.ubuntu.com/11432261/

**Comment by vincent-legoll** [comment]
BTW, I've already read the 2 other bug reports before logging my own because they did not really help me fix the problem...

**Comment by loomis** [comment]
The SlipStream build requires Maven 3.2+. Retrying with a more recent maven should fix the problem.

**Comment by konstan** [comment]
Have you tried upgrading maven to >3.0?

**Comment by vincent-legoll** [comment]
I'm already on mvn > 3.0.0 ;-)

But with 3.3.3 (most recent stable) it goes further...

Why not explicitely detecting mvn < 3.2 and telling the poor user ?

Because the original error message didn't give the slightest bit of a clue that this may be the problem...

Or at least put that in the README.md or INSTALL, but... [looking]... OK scratch that, it was there but removed about a month ago :-/

**Comment by loomis** [comment]
> Why not explicitely detecting mvn < 3.2 and telling the poor user ?

Maven version 3.2.0 is marked as a build prerequisite in the main `pom.xml` file.  Unfortunately maven, despite the documentation, does not fail the build if the prerequisite is not satisfied.

> Or at least put that in the README.md or INSTALL, but... [looking]... OK scratch that, it was there but removed about a month ago :-/

This information was removed from the `README.md` file at the same time a reference to the Developer Guide on the main SlipStream documentation web site was added in the "Getting Started" section.  

The Developer Guide mentions the requirement for maven v3.2.0:

  - In the maven section of the "Dependencies" chapter and
  - In the "Prerequisites" part of the "Source Code" chapter.

Nonetheless, I've now added a boxed warning in the maven section to make this requirement more apparent. 

I've also added a section to the "Dependencies" chapter describing exactly what packages are needed to build SlipStream on Ubuntu 14.04.  To build SlipStream, do
```
mvn clean install -DskipTests
```
This works correctly for me on a plain Ubuntu 14.04 machine.

Currently, one of our test dependencies currently requires Java 1.8, causing the tests to fail on a plain Ubuntu 14.04 machine.  I've asked the developer if a version of his library can be provided with Java 1.7 class files.  In the meantime, either avoid the tests (as above) or:

  - Follow one of the recipes on the web for installing OpenJDK or the Oracle JDK on Ubuntu 14.04 and
  - Then run the build and test with `mvn clean install`.

When testing with the Oracle JDK v1.8, this worked correctly for me.  Presumably it will also work with the OpenJDK 1.8, although I've not explicitly tested this.

The RPM packages will be built on Ubuntu if you include the `rpm` and `createrepo` packages on your system (as is documented).  However, those packages cannot be used to install and run SlipStream. Use the information in the "Running Locally" chapter for starting a local SlipStream server for tests.

**Comment by vincent-legoll** [comment]
Making progress, but  there's still a :
```
$ ~/bin/mvn-3.3.3 compile
[...]
[INFO] --- exec-maven-plugin:1.4.0:exec (cljs-build) @ SlipStreamUI ---
[...]
[DEBUG] Executing command line: [lein, do, deps, ,, cljsbuild, once]
That's not a task. Use "lein help" to list all tasks.
[...]
```
Please ask if more info is needed...

**Comment by vincent-legoll** [comment]
I fixed it with https://github.com/slipstream/SlipStreamUI/commit/4d2e5f7800d07f7b25132f32ac6c000ea0e1acbc

Is that OK ?

**Comment by vincent-legoll** [comment]
I downloaded lein from:
https://raw.githubusercontent.com/technomancy/leiningen/stable/bin/lein
put it in ~/bin and it now pass the SlipTreamUI compile step.

$ ~/bin/lein -v
Leiningen 2.5.1 on Java 1.7.0_79 OpenJDK 64-Bit Server VM

**Comment by vincent-legoll** [comment]
OKwith the new lein it builds properly
